# Generated by Django 4.1 on 2022-08-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="extenduser",
            name="is_vendor",
            field=models.BooleanField(default=False),
        ),
    ]
